### ISSUE TITLE
it fails to build docs on Ubuntu 16.04

### ISSUE THREAD

**Issue by trappedinspacetime** [sezero/nasm#1]
First of all, thank you for your asm repository. I tried to build it on my system. If I use `make` it builds well, but it fails to buid `make doc` with the following error:
      
    perl -I. ./rdsrc.pl -I./ dip nasmdoc.src
    Reading input...done.
    Fixing up cross-references...done.
    Sorting index tags...done.
    Producing Documentation Intermediate Paragraphs: done.
    perl -I. ./genps.pl -epsdir "." \
    	-headps ./head.ps \
    	-fontpath fontpath \
    	-fontmap Fontmap \
    	nasmdoc.dip > nasmdoc.ps
    : no font found of: SourceSansPro-Semibold, ClearSans-Bold, Arial-Bold, Helvetica-Bold
    Install one of these fonts or update psfonts.ph
    Makefile:69: recipe for target 'nasmdoc.ps' failed
    make[1]: *** [nasmdoc.ps] Error 29
    make[1]: Leaving directory '/home/trabzonspor/NewDesktop/Mart-2020/nasm/doc'
    Makefile:433: recipe for target 'doc' failed
    make: *** [doc] Error 2

How can I work around that dependency error?

**Comment by sezero** [comment]
> First of all, thank you for your asm repository. I tried to build it on my system.
> If I use `make` it builds well, but it fails to buid `make doc` with the following error:

This is just a mirror/fork of official nasm repo. You should file a
bug report at https://bugzilla.nasm.us/
(FWIW, I don't build the docs myself, so no idea.)

> make[1]: Leaving directory '/home/trabzonspor/NewDesktop/Mart-2020/nasm/doc'

( Eğer Fenerbahçeli olsaydın kesin bir şekilde yardım ederdim :) )

**Comment by xingfeT** [comment]
if your work in centos7
sudo dnf install adobe-source-sans-pro-fonts  perl-Font-TTF perl-Sort-Versions
